Updated omv-update-snaphost script

diff --git a/debian/omv-update-snaphost b/debian/omv-update-snaphost
--- a/debian/omv-update-snaphost
+++ b/debian/omv-update-snaphost
@@ -12,14 +12,22 @@ get_revision(){
 }
 
 get_debversion(){
-	[ -r "$1/debian/changelog" ] || return 1
-	sed -ne "1{s%^.*(%%;s%).*$%%;p}" "$1/debian/changelog"
+	if [ -d "$1/debian" ] ; then
+		[ -r "$1/debian/changelog" ] || return 1
+		sed -ne "1{s%^.*(%%;s%).*$%%;p}" "$1/debian/changelog"
+	else
+		echo "0"
+	fi
 	return 0
 }
 
 get_debname(){
-	[ -r "$1/debian/control" ] || return 1
-	sed -ne "/^Source:/{s%^.*:[[:blank:]]*%%;;p}" "$1/debian/control"
+	if [ -d "$1/debian" ] ; then
+		[ -r "$1/debian/control" ] || return 1
+		sed -ne "/^Source:/{s%^.*:[[:blank:]]*%%;;p}" "$1/debian/control"
+	else
+		echo "omv-extra-$1"
+	fi
 	return 0
 }
 
@@ -72,22 +80,12 @@ svn up || die "Error updating repo"
 for d in $(ls -1) ; do
 	if [ -d "$d" ] ; then
 		REV_NUM="$(get_revision "$d")" || die "Error getting revision number in $d"
-		if [ -d "$d/debian" ] ; then
-			# debian package, just one entity
-			DEB_NUM="$(get_debversion "$d")" || die "Unable to get debian version of $d"
-			DEB_NAME="$(get_debname "$d")" || die "Unable to get debian package name of $d"
-			TAR_VERSION="${DEB_NUM}+svn${REV_NUM}"
-			TAR_NAME="${DEB_NAME}"
-			do_tarball $d $REV_NUM $TAR_NAME $TAR_VERSION
-		else
-			# pack each file/dir
-			for f in $(ls -1 $d) ; do
-				REV_NUM="$(get_revision "$d/$f")" || die "Error getting revision number of $d/$f"
-				TAR_NAME="${d}-${f}"
-				TAR_VERSION="svn${REV_NUM}"
-				do_tarball $d $REV_NUM $TAR_NAME $TAR_VERSION
-			done
-		fi
+		# debian package, just one entity
+		DEB_NUM="$(get_debversion "$d")" || die "Unable to get debian version of $d"
+		DEB_NAME="$(get_debname "$d")" || die "Unable to get debian package name of $d"
+		TAR_VERSION="${DEB_NUM}+svn${REV_NUM}"
+		TAR_NAME="${DEB_NAME}"
+		do_tarball $d $REV_NUM $TAR_NAME $TAR_VERSION
 	fi
 done
 cd $CUR_DIR
